name: Deploy pages
on: push

permissions:
  contents: write

jobs:
  deploy-pages:
    name: Deploy Github Pages
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'nertsal'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            background/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
      # - name: Install WASM tools
      #   run: sudo apt-get update && sudo apt-get install binaryen
      - name: Install cargo-geng
        run: cargo install cargo-geng --git https://github.com/geng-engine/cargo-geng --rev 8e869f6508d39890a6f84122fb1c7f86a9da18da
      - name: Build background
        run: |
          cd background
          cargo geng build --release --platform web --out-dir target
          # wasm-opt -Os -o target/background.wasm target/background.wasm
          cd ..
          cp -r background/target/ website/static/background/
      - name: Zola Deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: website
